// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwECLTBxfTW0fEFUxmcde3EuZbmYPeouk',
    appId: '1:961448813024:android:1570843f8ac0681c3d8b85',
    messagingSenderId: '961448813024',
    projectId: 'shifumi-46359',
    databaseURL: 'https://shifumi-46359-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'shifumi-46359.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANh9706jjccMM850beepTJ5rBx9QuTmTk',
    appId: '1:961448813024:ios:cdfd6457c51ec10c3d8b85',
    messagingSenderId: '961448813024',
    projectId: 'shifumi-46359',
    databaseURL: 'https://shifumi-46359-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'shifumi-46359.appspot.com',
    iosClientId: '961448813024-g01al8kcjb9f3c5nvf9i4doon7oljn37.apps.googleusercontent.com',
    iosBundleId: 'fr.lennylouis.shifumi.shifumi',
  );
}
